# Code Generated by Sidekick is for learning and experimentation purposes only.
variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t3.small"
}

variable "root_volume_size" {
  description = "Root EBS volume size in GiB"
  type        = number
  default     = 10
}

variable "dynatrace_tenant" {
  description = "Dynatrace tenant URL (e.g., https://abc123.live.dynatrace.com)"
  type        = string
}

variable "dynatrace_token" {
  description = "Dynatrace API token for OneAgent install"
  type        = string
  sensitive   = true
}
